--Vamos criar a visão com a consulta que retorna as qtde de produto vendidadas agregadas. 
--Não se esqueça de criar um apelido para o agregador SUM(QUANTIDADE):

CREATE VIEW TINA_VIEW_QUANTIDADE_PRODUTOS AS 
SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, 
SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL 
FROM TINA_TB_ITENS_NOTAS_FISCAIS INF
INNER JOIN TINA_TB_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO;

--Usando essa visão, selecione o que a consulta original no enunciado faz:
SELECT * FROM TINA_VIEW_QUANTIDADE_PRODUTOS
WHERE QUANTIDADE_TOTAL > 80000 
ORDER BY QUANTIDADE_TOTAL DESC
