--RIGHT JOIN 
--Qual seria a consulta para listar apenas a cidade que não teve nenhum candidato votado?
--COMPARA A CIDADES COM AS CIDADES DO CANDIDATO, TRAZENDO A CIDADE QUE ESTIVER NULL
SELECT CI.CIDADE 
FROM CANDIDATO CA 
RIGHT JOIN CIDADE CI 
ON CA.CIDADE = CI.CIDADE 
WHERE CA.CIDADE IS NULL;
