--LEFT JOIN: Retorna todos os registros da tabela esquerda e os registros correspondentes da tabela direita.
--Em resumo, a cláusula LEFT JOIN retorna todas as linhas da tabela “esquerda” A e as linhas correspondentes ou valores NULL da tabela “esquerda” A
SELECT <select_list>
FROM Tabela A
LEFT JOIN Tabela B
ON A.Key = B.Key --cada linha da tabela A, a consulta a compara com todas as linhas da tabela B
-------------------

INSERT INTO TINA_TB_CLIENTES 
(CPF, NOME, ENDERECO_1, ENDERECO_2, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, 
SEXO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA) 
VALUES ('23412632331', 'Juliana Silva', 'R. Tramandai', '', 'Bangu', 'Rio de Janeiro', 
'RJ', '23400000', TO_DATE('1989-02-04','YYYY-MM-DD'), 28, 'F', 180000.0000, 24500, 0);
---------------------------

SELECT * FROM TINA_TB_CLIENTES

SELECT COUNT(*) FROM TINA_TB_CLIENTES -- CONTA TODOS OS CLIENTES QUE TEM NO BANCO

--SELECIONA AS NOTAS FISCAIS DE ACORDO COM O CPF
SELECT 
       TC.CPF AS CPF_DO_CLIENTE,
       TC.NOME AS NOME_DO_CLIENTE,
       NF.CPF AS CPF_NOTAS_FISCAIS
FROM TINA_TB_CLIENTES TC
INNER JOIN TINA_TB_NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF
--MOSTRA 20 NOTAS 

--SELECIONA AS NOTAS FISCAIS DE ACORDO COM O CPF PORÉM NÃO MOSTRA OS REPETIDOS
SELECT DISTINCT
       TC.CPF AS CPF_DO_CLIENTE,
       TC.NOME AS NOME_DO_CLIENTE,
       NF.CPF AS CPF_NOTAS_FISCAIS
FROM TINA_TB_CLIENTES TC
INNER JOIN TINA_TB_NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF
--MOSTRA 15

--USANDO LEFT JOIN
--DEPOIS DE INCLUSO UM CLIENTE NOVO E SEM NOTA, MOSTRA TODOS OS CLIENTES INDEPENDENTE SE COMPRARAM
SELECT DISTINCT
       TC.CPF AS CPF_DO_CLIENTE,
       TC.NOME AS NOME_DO_CLIENTE,
       NF.CPF AS CPF_NOTAS_FISCAIS
FROM TINA_TB_CLIENTES TC
LEFT JOIN TINA_TB_NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF
--MOSTRA 16 CLIENTES E O CLIENTE INSERIDO COM VALOR NULL - VAZIO

--DEPOIS DE INCLUSO UM CLIENTE NOVO E SEM NOTA MOSTRA, MOSTRA OS CLIENTES QUE NÃO COMPRARAM
--INCLUSO A CONDIÇÃO DE CLIENTE SEM NOTA 'WHERE NF.CPF IS NULL;'
SELECT 
       TC.CPF AS CPF_DO_CLIENTE,
       TC.NOME AS NOME_DO_CLIENTE
FROM TINA_TB_CLIENTES TC
LEFT JOIN TINA_TB_NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF
WHERE NF.CPF IS NULL;
--MOSTRA SOMENTE O CLIENTE SEM NOTA
