
--Inner Join é a intercecção do resultado comum

--LEFT JOIN VAI TRAZER TODOS OS VALORES
--SELECIONA TODOS OS VENDEDORES E TODOS OS CLIENTES
--COLOCANDO OS QUE TEM O MESMO BAIRRO JUNTOS
--escreve null quando o valor da tabela direita não existir
SELECT 
TV.NOME AS NOME_VENDEDOR,
TV.BAIRRO AS BAIRRO_VENDEDOR,
TC.NOME AS NOME_CLIENTE,
TC.BAIRRO AS BAIRRO_CLIENTE
FROM TINA_TB_CLIENTES TC
LEFT JOIN TINA_TB_VENDEDORES TV
ON TV.BAIRRO = TC.BAIRRO

--RIGHT JOIN VAI TRAZER TODOS OS VALORES DA TABELA DA DIREITA
--SELECIONA TODOS OS VENDEDORES E SOMENTE OS CLIENTES COM BAIRROS IGUAIS
----escreve null quando o valor da tabela esquena não existir
SELECT 
TV.NOME AS NOME_VENDEDOR,
TV.BAIRRO AS BAIRRO_VENDEDOR,
TC.NOME AS NOME_CLIENTE,
TC.BAIRRO AS BAIRRO_CLIENTE
FROM TINA_TB_CLIENTES TC
RIGHT JOIN TINA_TB_VENDEDORES TV
ON TV.BAIRRO = TC.BAIRRO

--lEFT JOIN VAI TRAZER TODOS OS VALORES DA TABELA DA ESQUERDA
--SELECIONA TODOS OS CLIENTES E SOMENTE OS VENDENDORES COM BAIRROS IGUAIS
SELECT 
TV.NOME AS NOME_VENDEDOR,
TV.BAIRRO AS BAIRRO_VENDEDOR,
TC.NOME AS NOME_CLIENTE,
TC.BAIRRO AS BAIRRO_CLIENTE
FROM TINA_TB_CLIENTES TC
LEFT JOIN TINA_TB_VENDEDORES TV
ON TV.BAIRRO = TC.BAIRRO


--FULL JOIN VAI TRAZER TODOS OS VALORES DA TABELA DA ESQUERDA
--SELECIONA TODOS OS CLIENTES E OS VENDENDORES COM BAIRROS IGUAIS
--SELECIONA OS CLIENTES QUE NÃO TEM VENDEDOR COLOCANDO NULL
--SELECIONA OS VENDEDORES QUE NÃO TEM CLIENTE COLOCANDO NULL
SELECT 
TV.NOME AS NOME_VENDEDOR,
TV.BAIRRO AS BAIRRO_VENDEDOR,
TC.NOME AS NOME_CLIENTE,
TC.BAIRRO AS BAIRRO_CLIENTE
FROM TINA_TB_CLIENTES TC
FULL JOIN TINA_TB_VENDEDORES TV
ON TV.BAIRRO = TC.BAIRRO


--CROSS JOIN FAZ ANALISE COMBINTÓRIA COM TODOS DA ESQUERDA E TODOS DA DIREITA

