--SELECIONANDO CLIENTES QUE TEM SEDE FUNCIONÁRIOS
--PRIMEIRO BUSCA OS BAIRROS DOS VENDEDORES
SELECT DISTINCT BAIRRO FROM TINA_TB_VENDEDORES
-- eM SEGUIDA UTILIZA A BUSCA DO BAIRRO POR VENDEDOR NA TABELA DE CLIENTE
--ASSIM O BAIRRO DO CLIENTE SERÁ DO BAIRRO DO VENDEDOR
SELECT * FROM TINA_TB_CLIENTES
WHERE BAIRRO IN (SELECT DISTINCT BAIRRO FROM TINA_TB_VENDEDORES);

--Veja a consulta abaixo, que foi resposta de uma atividade anterior:

SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, TP.SABOR,
SUM(INF.QUANTIDADE) 
FROM TINA_TB_ITENS_NOTAS_FISCAIS INF
INNER JOIN TINA_TB_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, TP.SABOR
HAVING SUM(INF.QUANTIDADE) >= 39400 
ORDER BY SUM(INF.QUANTIDADE) DESC;

--Ela nos dá os produtos cuja soma das vendas são maiores que 39400.
--Liste os sabores dos produtos que são selecionados nesta consulta.


--Resolução
SELECT DISTINCT SABOR FROM TINA_TB_PRODUTOS WHERE
CODIGO_DO_PRODUTO IN (
                       SELECT INF.CODIGO_DO_PRODUTO FROM TINA_TB_ITENS_NOTAS_FISCAIS INF
                       INNER JOIN TINA_TB_PRODUTOS TP 
                       ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
                       GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO 
                       HAVING SUM(INF.QUANTIDADE) > 39400);
