--SELECIONANDO TODAS AS EMBALAGENS, MOSTRANDO O TOTAL SOMADO PELO PREÇO DE LISTA
SELECT EMBALAGEM, 
SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TINA_TB_PRODUTOS 
GROUP BY EMBALAGEM
-- lATA = 19, GARRAFA = 76, PET = 249

--SELECIONANDO AS EMBALAGENS E LISTANDO PELO PREÇO DE LISTA MAIOR QUE 80 USANDO HAVING
SELECT EMBALAGEM,
SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TINA_TB_PRODUTOS
GROUP BY EMBALAGEM
HAVING SUM(PRECO_DE_LISTA) >80 -- INCLUSO A CONDIÇÃO NOS DADOS AGRUPADOS

--SELECIONANDO AS EMBALAGENS E LISTANDO AS MAIORES QUE 80 COM SUBCONSULTA
SELECT SOMA_EMBALAGENS.EMBALAGEM, SOMA_EMBALAGENS.SOMA_PRECO
FROM (
       SELECT EMBALAGEM, 
       SUM(PRECO_DE_LISTA) AS SOMA_PRECO
       FROM TINA_TB_PRODUTOS 
       GROUP BY EMBALAGEM
       ) SOMA_EMBALAGENS
WHERE SOMA_EMBALAGENS.SOMA_PRECO >=80.

