INSERT INTO TINA_TB_PRODUCT
(ID_PRODUCT, DS_PRODUCT, DS_PACKING, DS_SIZE, DS_FLAVOR, COST_UNIT)
VALUES
('544931', 'Frescor do Verão - 350 ml - Limão', 'PET', '350 ml','Limão',3.20);

INSERT INTO TINA_TB_PRODUCT
(ID_PRODUCT, DS_PRODUCT, DS_PACKING, DS_SIZE, DS_FLAVOR, COST_UNIT)
VALUES
('1078681', 'Frescor do Verão - 470 ml - Morango', 'Lata', '470 ml','Morango',5.18);

SELECT * FROM TINA_TB_PRODUCT;

UPDATE TINA_TB_PRODUCT
       SET DS_PACKING = 'Garrafa',
           COST_UNIT = 2.46 
       WHERE ID_PRODUCT = '544931';

UPDATE TINA_TB_PRODUCT
       SET DS_PACKING = 'Garrafa',
       WHERE ID_PRODUCT = '1078681';
