
INSERT INTO TB_PRODUCT
(ID_PRODUCT, DS_PRODUCT, DS_PACKING, DS_SIZE, DS_FLAVOR, COST_UNIT)
VALUES
('1040107','Light - 350 ml - Melancia', 'Lata',
'350 ml','Melancia',4.56);

INSERT INTO TB_PRODUCT
(ID_PRODUCT, DS_PRODUCT, DS_PACKING, DS_SIZE, DS_FLAVOR, COST_UNIT)
VALUES
('1037797','Clean - 2 Litros - Laranja', 'PET',
'2 Litros','Laranja',16.01);

INSERT INTO TB_PRODUCT
(ID_PRODUCT, DS_PRODUCT, DS_PACKING, DS_SIZE, DS_FLAVOR, COST_UNIT)
VALUES
('1000889','Sabor da Montanha - 700 ml - Uva', 'Garrafa',
'700 ml','Uva',6.31);

INSERT INTO TB_PRODUCT
(ID_PRODUCT, DS_PRODUCT, DS_PACKING, DS_SIZE, DS_FLAVOR, COST_UNIT)
VALUES
('1004327','Videira do Campo - 1,5 Litros - Melância', 'PET',
'1,5 Litros','Melância',19.51);

SELECT * FROM TB_PRODUCT;
