CREATE TABLE TINA_PRODUTOS
(CODIGO VARCHAR(10)NOT NULL,
DESCRICAO VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL,
PRECO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO));

CREATE TABLE TAB_EMPRESA
(cod_empresa varchar(5)
,nome_empresa varchar(50)
,PRIMARY KEY (cod_empresa));

ALTER TABLE TAB_EMPRESA RENAME TO TINA_TB_EMPRESA

CREATE TABLE TAB_DEPARTAMENTO
(cod_departamento varchar(5)
,nome_departamento varchar(50)
,cidade_departamento varchar(50)
,cod_empresa varchar(5)
,PRIMARY KEY (cod_departamento));


ALTER TABLE TAB_DEPARTAMENTO RENAME TO TINA_TB_DEPARTAMENTO

CREATE TABLE TINA_TB_PROJETO
(cod_projeto varchar(5)
,nome_projeto varchar(50)
,orcamento_projeto float
,data_inicio_projeto date
,cod_departamento varchar(5)
,PRIMARY KEY (cod_projeto));

ALTER TABLE TAB_PROJETO RENAME TO TINA_TB_PROJETO

CREATE TABLE TAB_FUNCIONARIO 
(
  COD_FUNCIONARIO VARCHAR(5) NOT NULL 
, NOME_FUNCIONARIO VARCHAR(50) 
, DATA_ADMISSAO DATE 
, COD_DEPARTAMENTO VARCHAR(5) 
, CONSTRAINT TAB_FUNCIONARIO_PK PRIMARY KEY 
  (
    COD_FUNCIONARIO 
  )
  ENABLE 
);

ALTER TABLE TAB_FUNCIONARIO RENAME TO TINA_TB_FUNCIONARIO

CREATE TABLE TINA_TB_DEPENDENTE 
(
  COD_DEPENDENTE VARCHAR(5) NOT NULL 
, NOME_DEPENDENTE VARCHAR(50) 
, TIPO_DEPENDENTE VARCHAR(50) 
, IDADE_DEPENDENTE INTEGER 
, COD_FUNCIONARIO VARCHAR(5) 
, CONSTRAINT TINA_TB_DEPENDENTE_PK PRIMARY KEY 
  (
    COD_DEPENDENTE 
  )
  ENABLE 
);

ALTER TABLE TAB_DEPENDENTE RENAME TO TINA_TB_DEPENDENTE
