ALTER TABLE TINA_TB_DEPARTAMENTO
ADD CONSTRAINT FK_TINA_TB_DEPARTAMENTO
FOREIGN KEY (cod_empresa) 
REFERENCES TINA_TB_EMPRESA (cod_empresa);

ALTER TABLE TINA_TB_PROJETO
ADD CONSTRAINT FK_TINA_TB_DEP_PROJETO 
FOREIGN KEY (cod_departamento) 
REFERENCES TINA_TB_DEPARTAMENTO (cod_departamento);

ALTER TABLE TINA_TB_FUNCIONARIO
ADD CONSTRAINT FK_TINA_TB_DEP_FUNCIONARIO 
FOREIGN KEY (cod_departamento) 
REFERENCES TINA_TB_DEPARTAMENTO (cod_departamento);

ALTER TABLE TINA_TB_DEPENDENTE
ADD CONSTRAINT FK_TINA_TB_FUNC_DEPENDENTE 
FOREIGN KEY (cod_funcionario) 
REFERENCES TINA_TB_FUNCIONARIO (cod_funcionario);


