ALTER TABLE TINA_TB_DEPARTAMENTO rename column CIDADE_DEPARTAMENTO to CIDADE

ALTER TABLE TINA_TB_PROJETO RENAME COLUMN ORCAMENTO_PROJETO TO ORCAMENTO;

ALTER TABLE TINA_TB_PROJETO RENAME COLUMN DATA_INICIO_PROJETO TO DATA_INICIO;

ALTER TABLE TINA_TB_DEPENDENTE RENAME COLUMN TIPO_DEPENDENTE TO TIPO;

ALTER TABLE TINA_TB_DEPENDENTE RENAME COLUMN IDADE_DEPENDENTE TO IDADE;
