--Esquema de venda de suco de frutas
--Tabela que se chama "SEGMERCADO" e a outra tabela, "CLIENTE". 
--A "SEGMERCADO" possui a lista de segmentos de mercado. 
--chave estrangeira do campo "ID" da tabela "SEGMERCADO" no campo "SegMercado_id" da tabela "CLIENTE".


CREATE TABLE PRODUTO_EXERCICIO
(
COD VARCHAR2(5)
,DESCRICAO VARCHAR2(100)
,CATEGORIA VARCHAR2(100)
);

CREATE TABLE PRODUTO_VENDA_EXERCICIO
(
ID NUMBER(5)
,COD_PRODUTO VARCHAR2(5)
,DATA DATE
,QUANTIDADE FLOAT
,PRECO FLOAT
,VALOR_TOTAL FLOAT
,PERCENTUAL_IMPOSTO FLOAT
);

-- Montando as chaves primárias:

ALTER TABLE PRODUTO_EXERCICIO ADD CONSTRAINT PRODUTO_EXERCICIO_COD_PKPRIMARY KEY (COD);
ALTER TABLE PRODUTO_VENDA_EXERCICIO ADD CONSTRAINT PRODUTO_VENDA_EXERCICIO_ID_PKPRIMARY KEY (ID);

--Montando as chaves estrangeiras
ALTER TABLE PRODUTO_VENDA_EXERCICIO ADD CONSTRAINT PRODUTO_VENDA_EXERCICIO_PRODUTO_EXERCICIO_CODFOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO_EXERCICIO (COD);
