DECLARE
  v_ID TINA_TB_SEGMERCADO.ID%TYPE := 3;
  v_DESCRICAO TINA_TB_SEGMERCADO.DESCRICAO%TYPE := 'Atacadista';
BEGIN
  UPDATE TINA_TB_SEGMERCADO SET DESCRICAO = UPPER(v_DESCRICAO) WHERE ID = v_ID;
  v_ID := 1;
  v_DESCRICAO := 'Varejista';
  UPDATE TINA_TB_SEGMERCADO SET DESCRICAO = UPPER(v_DESCRICAO) WHERE ID = v_ID;
  v_ID := 2;
  v_DESCRICAO := 'Industrial';
  UPDATE TINA_TB_SEGMERCADO SET DESCRICAO = UPPER(v_DESCRICAO) WHERE ID = v_ID;
  COMMIT;
END;

select * from TINA_TB_SEGMERCADO
