DECLARE
  v_COD TINA_TB_PRODUTOS.CODIGO_DO_PRODUTO%type;
BEGIN
   v_COD := '41232';
   UPDATE TINA_TB_PRODUTOS SET NOME_DO_PRODUTO = REPLACE(NOME_DO_PRODUTO,'-','>') WHERE CODIGO_DO_PRODUTO = v_COD;
    v_COD := '32223';
   UPDATE TINA_TB_PRODUTOS SET NOME_DO_PRODUTO = REPLACE(NOME_DO_PRODUTO,'-','>') WHERE CODIGO_DO_PRODUTO = v_COD;
   COMMIT;
END;

SELECT * FROM TINA_TB_PRODUTOS
