SELECT * FROM TINA_TB_PRODUTOS

DECLARE 
  v_CODIGO NVARCHAR2(10) := '41232';
  v_NOME NVARCHAR2(50) := 'SABOR DE VERAO - LARANJA - 1 LITRO';
  v_EMBALAGEM NVARCHAR2(20) := 'PET';
  v_TAMANHO NVARCHAR2(10) := '1 LITRO';
  v_SABOR VARCHAR(100) := 'SUCO DE FRUTAS';
  v_PRECO float := 10;
BEGIN
  INSERT INTO TINA_TB_PRODUTOS
  (codigo_do_produto, nome_do_produto, SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA) 
  VALUES 
  (v_CODIGO, v_NOME, v_EMBALAGEM, v_TAMANHO, v_SABOR, v_PRECO);
  COMMIT;
END;
