--COMANDO PARA ATUALIZAR AS INFORMAÇÕES
UPDATE <TABELA>
SET <CAMPO_ALTERADO>=<VALOR_ALTERADO>
WHERE <CONDIÇÃO DO CAMPO>

SELECT * FROM TINA_TB_PRODUTOS
WHERE CODIGO_DO_PRODUTO = '1040107'

--COMANDO UPDATE NA TABELA DE PRODUTOS
UPDATE TINA_TB_PRODUTOS 
SET PRECO_DE_LISTA = 5.2
WHERE CODIGO_DO_PRODUTO = '1040107'

UPDATE TINA_TB_PRODUTOS
SET SABOR = 'Laranja',
    embalagem = 'PET'
WHERE CODIGO_DO_PRODUTO = '1040107'

--CONSULTA QUE ALTERA O CAMPO DESCRICAO
SELECT NOME_DO_PRODUTO, 
REPLACE(NOME_DO_PRODUTO, 'Melancia', 'Laranja') 
FROM TINA_TB_PRODUTOS
WHERE CODIGO_DO_PRODUTO = '1040107'

--ATUALIZA O NOME DO PRODUTO COM A FUNCAO
UPDATE TINA_TB_PRODUTOS 
SET NOME_DO_PRODUTO =
REPLACE(NOME_DO_PRODUTO, 'Melancia', 'Laranja')
WHERE CODIGO_DO_PRODUTO = '1040107'

--atualiza o preco_lista dos produtos que tem sabor de maracuja
SELECT * FROM TINA_TB_PRODUTOS
WHERE SABOR = 'Maracuja'

UPDATE TINA_TB_PRODUTOS 
SET PRECO_DE_LISTA = PRECO_DE_LISTA *1.10
WHERE SABOR = 'Maracuja'

