CREATE TABLE TINA_TB_PROJETO_ORCAMENTO
(cod_projeto VARCHAR(5), percentual_novo_orcamento FLOAT);

INSERT INTO TINA_TB_PROJETO_ORCAMENTO VALUES ('P0001',0.2);
INSERT INTO TINA_TB_PROJETO_ORCAMENTO VALUES ('P0002',0.1);
INSERT INTO TINA_TB_PROJETO_ORCAMENTO VALUES ('P0003',-0.1);
INSERT INTO TINA_TB_PROJETO_ORCAMENTO VALUES ('P0005',0.23);
INSERT INTO TINA_TB_PROJETO_ORCAMENTO VALUES ('P0007',0.09);
INSERT INTO TINA_TB_PROJETO_ORCAMENTO VALUES ('P0008',-0.03);
INSERT INTO TINA_TB_PROJETO_ORCAMENTO VALUES ('P0009',-0.05);
INSERT INTO TINA_TB_PROJETO_ORCAMENTO VALUES ('P0011',0.123);

SELECT * FROM TINA_TB_PROJETO_ORCAMENTO

--Como deve ser o comando para fazer o UPDATE no orçamento dos projetos 
--na tabela TAB_PROJETO, baseado na tabela acima?
UPDATE TAB_PROJETO P 
SET P.ORCAMENTO = P.ORCAMENTO * ( 1 + 
(SELECT TBO.percentual_novo_orcamento FROM TAB_PROJETO_ORCAMENTO TBO
WHERE P.COD_PROJETO = TBO.COD_PROJETO))
WHERE EXISTS
(SELECT 1 FROM TAB_PROJETO_ORCAMENTO TBO
WHERE P.COD_PROJETO = TBO.COD_PROJETO);
