--Queremos acrescentar 1 ano à idade de todos os dependentes. 
--O ano virou e precisamos atualizar a tabela. 
--Qual seria o comando mais apropriado para fazer isso? 
UPDATE TAB_DEPENDENTE SET IDADE = IDADE + 1;

--UPDATE DE UM TABELA COM BASE EM OUTRA TABELA
--TABELA DESTINO PARA FONTE
--DOWNLOAD INCLUI_TABELA_VENDEDORES_FONTE

SELECT * FROM TINA_TB_VENDEDORES_FONTE

SELECT 
TV.MATRICULA AS MATRICULA_VENDEDORES,
TV.DE_FERIAS AS FERIAS_VENDEDORES,
TVF.DE_FERIAS AS FERIAS_FONTE
FROM TINA_TB_VENDEDORES TV
INNER JOIN TINA_TB_VENDEDORES_FONTE TVF
ON TV.MATRICULA = SUBSTR(TVF.MATRICULA,3,3);

UPDATE VENDEDORES V
INNER JOIN TABELA_DE_VENDEDORES_FONTE TVF
ON V.MATRICULA = SUBSTR (TVF.MATRICULA,3,3);
SET V.FERIAS = TVF.DE_FERIAS;

--EXISTS
SELECT V.MATRICULA AS MATRICULA_VENDEDORES,
V.DE_FERIAS AS FERIAS_VENDEDORES
FROM TINA_TB_VENDEDORES V
WHERE EXISTS
(select 1 from TINA_TB_VENDEDORES_FONTE tvf 
where v.matricula = substr(tvf.matricula, 3, 3));

INSERT INTO  TINA_TB_VENDEDORES_FONTE
VALUES ('00239', 'JOSE MARIA', 0.12, TO_DATE('2018-01-01','YYYY-MM-DD'),1,'TIJUCA');
