
-- TANTO NA CONSULTA COMO NO UPDATE O WHERE FUNCIONA COMO UM FILTRO, PARA SER MOSTRADO APENAS NAQUELE VALOR ESPECÍFICO
-- WHERE USADO EM UPDATE, DELETE E SELECT SÃO FUNDAMENTAIS

SELECT * FROM TINA_TB_PRODUTOS P
WHERE P.PRODUTO LIKE '10%'
AND SABOR = 'Limão'

UPDATE TINA_TB_PRODUTOS
SET SABOR = 'Cítricos'
WHERE SABOR = 'Limão'
