--FUNÇÕES DO TIPO TEXTO: STRING
--CAMPO UNICO COM DOIS OU TRÊS CAMPOS CONCATENADAS

SELECT FUNCTION <CAMPO> 
FROM TABELA

--CONCAT SOMENTE ACEITA DOIS PARAMETROS POR FUNCAO CONCAT
SELECT ENDERECO_1, BAIRRO, CONCAT(ENDERECO_1,'') FROM TINA_TB_CLIENTES

--PARA CONSEGUIRMOS INCLUIR MAIS PARAMETROS INCLUIR FUNCAO CONCAT
SELECT ENDERECO_1, BAIRRO, CONCAT(CONCAT(ENDERECO_1,' - '), BAIRRO) FROM TINA_TB_CLIENTES

SELECT ENDERECO_1 || ' ' || BAIRRO || ' ' || CIDADE || ' ' || ESTADO || '-' || CEP FROM TINA_TB_CLIENTES
