-->https://docs.oracle.com/javadb/10.8.3.0/ref/rrefsqlj29930.html
--UCASE or UPPER ( CharacterExpression )
--FUNÇÕES DO TIPO TEXTO: STRING
SELECT FUNCTION <CAMPO>  FROM TABELA

SELECT NOME, LOWER(NOME), BAIRRO, UPPER(BAIRRO) FROM TINA_TB_VENDEDORES

SELECT * FROM TINA_TB_VENDEDORES

SELECT * FROM TINA_TB_PRODUTOS

