--FUNÇÕES DO TIPO TEXTO: STRING
--COLOCA A 1A LETRA DAS PALAVRAS DO CAMPO EM MAIUSCULAS


SELECT FUNCTION <CAMPO> 
FROM TABELA


SELECT NOME_DO_PRODUTO, INITCAP(NOME_DO_PRODUTO) FROM TINA_TB_PRODUTOS
