--FUNÇÕES DO TIPO TEXTO: STRING (texto)
-->https://docs.oracle.com/javadb/10.8.3.0/ref/rrefsqlj42049.html
--LCASE or LOWER ( CharacterExpression ) 

SELECT FUNCTION <CAMPO> FROM TABELA
--FUNCTION LOWER, AO REFERENCIAR UM CAMPO DEVERÁ SER DO TIPO STRING
--OS CAMPOS DO TIPO STRING SERÃO MOSTRADOS COM VALORES EM MINÚSCULO
SELECT NOME, LOWER(NOME) FROM TINA_TB_VENDEDORES

SELECT * FROM TINA_TB_VENDEDORES

SELECT * FROM TINA_TB_PRODUTOS

SELECT LOWER(EMBALAGEM) FROM TINA_TB_PRODUTOS
