ALTER TABLE TINA_TB_SELLER
ADD (DT_ADMISSAO DATE);

ALTER TABLE TINA_TB_SELLER
ADD (DE_FERIAS VARCHAR(1));

SELECT * FROM TINA_TB_SELLER

INSERT INTO TINA_TB_SELLER
(ID_SELLER, NM_SELLER, VL_COMISSION_PERC, DT_ADMISSAO, DE_FERIAS)
VALUES
('00238','Péricles Alves', 0.11, '21/08/2016', 'N');

UPDATE TINA_TB_SELLER
SET NM_SELLER = 'Roberta Martins',
    VL_COMISSION_PERC = 0.11,
    DT_ADMISSAO = '18/03/2017',
    DE_FERIAS = 'S'
WHERE ID_SELLER = 00237


UPDATE TINA_TB_SELLER
SET NM_SELLER = 'Márcio Almeida Silva',
    VL_COMISSION_PERC = 0.08,
    DT_ADMISSAO = '15/08/2014',
    DE_FERIAS = 'N'
WHERE ID_SELLER = 00235

UPDATE TINA_TB_SELLER
SET NM_SELLER = 'Cláudia Morais ',
    VL_COMISSION_PERC = 0.08,
    DT_ADMISSAO = '17/09/2013',
    DE_FERIAS = 'S'
WHERE ID_SELLER = 00236

UPDATE TINA_TB_SELLER
SET NM_SELLER = 'Péricles Alves',
    VL_COMISSION_PERC = 0.11,
    DT_ADMISSAO = '21/08/2016',
    DE_FERIAS = 'N'
WHERE ID_SELLER = 00238
    
    
