UPDATE TINA_TB_SELLER
       SET VL_COMISSION_PERC = 0.11
       WHERE ID_SELLER = '00236';
       
UPDATE TINA_TB_SELLER
       SET NM_SELLER = 'José Geraldo da Fonseca Junior'
       WHERE ID_SELLER = '00237';

SELECT * FROM TINA_TB_SELLER
