INSERT INTO TB_SELLER
(ID_SELLER, NAME_SELLER, COMISSION_PERC)
VALUES
('00237','José Geraldo da Fonseca', '10');

INSERT INTO TB_SELLER
(ID_SELLER, NAME_SELLER, COMISSION_PERC)
VALUES
('00235','Márcio Almeida Silva', '8');

INSERT INTO TB_SELLER
(ID_SELLER, NAME_SELLER, COMISSION_PERC)
VALUES
('00236','Cláudia Morais', '8');

SELECT * FROM TB_SELLER
