SELECT * FROM TINA_TB_COSTUMER

ALTER TABLE TINA_TB_COSTUMER ADD CONSTRAINT PK_TINA_TB_COSTUMER PRIMARY KEY (ID_CPF);

ALTER TABLE TINA_TB_COSTUMER ADD CONSTRAINT CK_ESTADO CHECK (ESTADO IN ('RJ','SP','MG','ES', 'SC'));

ALTER TABLE TINA_TB_COSTUMER 
ADD DT_NASC DATE;

INSERT INTO TINA_TB_COSTUMER
(ID_CPF, DS_NOME, DS_ENDERECO1, DS_ENDERECO2, BAIRRO, CIDADE, 
ESTADO, CEP, IDADE, DS_SEXO, VL_LIMITE_CREDITO, VL_COMPRA, PR_COMPRA, DT_NASC)
VALUES
('00388934505', 'JOÃO SILVA', 'RUA TESTES', NULL, 'SOL', 'BELEM', 'RJ', '22222222', 53, 'M', 10000.00, 2000, 0,'12/10/1965');

SELECT TO_CHAR(DT_NASC, 'MM') FROM TINA_TB_COSTUMER --TO_CHAR (CAMPO, 'MM') INDICA ONDE ESTÁ O MES NO CAMPO DATA

INSERT INTO TINA_TB_COSTUMER
(ID_CPF, DS_NOME, DS_ENDERECO1, DS_ENDERECO2, BAIRRO, CIDADE, 
ESTADO, CEP, IDADE, DS_SEXO, VL_LIMITE_CREDITO, VL_COMPRA, PR_COMPRA, DT_NASC)
VALUES
('09998934666', 'ANA MARIA SILVA', 'RUA TESTES 2', NULL, 'LUA', 'GLORIA', 'RJ', '33333333', 
40, 'F', 5000.00, 1000, 0, TO_DATE('12/10/1980', 'MM/DD/YYYY'));

-- TO_DATE('12/10/1980', 'DD/MM/YYYY')) FORÇA A SALVAR NO FORMATO INDICADO

SELECT TO_CHAR(DT_NASC, 'MM') FROM TINA_TB_COSTUMER --TO_CHAR (CAMPO, 'MM') INDICA ONDE ESTÁ O MES NO CAMPO DATA
