SELECT * FROM TINA_TB_PRODUCT;

UPDATE TINA_TB_PRODUCT
       SET DS_PACKING = 'Garrafa',
           COST_UNIT = 2.46 
       WHERE ID_PRODUCT = '544931';

UPDATE TINA_TB_PRODUCT
       SET DS_PACKING = 'Garrafa',
       WHERE ID_PRODUCT = '1078681';
