CREATE TABLE TB_COSTUMMER
(ID VARCHAR(11),
NAME VARCHAR(100),
ADRESS VARCHAR(150),
ADRESS2 VARCHAR(150),
NBHOOD VARCHAR(50),
CITY VARCHAR(50),
PROVINCE VARCHAR(50),
ZIPCODE VARCHAR(10),
AGE INT,
GENRER VARCHAR(1),
CREDIT_LIMIT FLOAT,
PURCHASE_VALUE FLOAT,
FIRST_BUY NUMBER(1))


SELECT * FROM TB_COSTUMMER
