CREATE TABLE TB_COSTUMER3
(ID_CPF VARCHAR(11),
NOME VARCHAR(100),
ENDERECO1 VARCHAR(150),
ENDERECO2 VARCHAR(150),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR(2),
CEP VARCHAR(8),
IDADE INT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUME_COMPRA FLOAT,
PRIMEIRA_COMPRA NUMBER(1))

ALTER TABLE TB_COSTUMER 
RENAME COLUMN SEX0 TO DS_SEXO;
--RENAME COLUMN NOME TO DS_NOME, 
--RENAME COLUMN ENDERECO1 TO DS_ENDERECO1,
--RENAME COLUMN ENDERECO2 TO DS_ENDERECO2,
RENAME COLUMN BAIRRO TO DS_BAIRRO,
RENAME COLUMN CIDADE TO DS_CIDADE;
RENAME COLUMN ESTADO TO DS_ESTADO,
RENAME COLUMN CEP TO ID_CEP,
RENAME COLUMN IDADE TO DS_IDADE,
RENAME COLUMN SEX0 TO DS_SEXO;

