--O departamento de RH nos passou a seguinte tabela com a lista de funcionários desligados no mês 


--Primeiramente, excluímos os dependentes,
-- para depois excluir os funcionários que estão na tabela TAB_RH_DEMITIDOS:
DELETE FROM TAB_DEPENDENTE TD WHERE
TD.COD_FUNCIONARIO IN (
SELECT TD.COD_FUNCIONARIO FROM TAB_DEPENDENTE TD INNER JOIN TAB_RH_DEMITIDOS TRD
ON TD.COD_FUNCIONARIO = TRD.COD_FUNCIONARIO);

DELETE FROM TAB_FUNCIONARIO TF WHERE
TF.COD_FUNCIONARIO IN (
SELECT TF.COD_FUNCIONARIO FROM TAB_FUNCIONARIO TF INNER JOIN TAB_RH_DEMITIDOS TRD
ON TF.COD_FUNCIONARIO = TRD.COD_FUNCIONARIO)
COMMIT;--DEPOIS DE COMITAR A ALTERAÇÃO PASSARÁ A SER VALIDA

--CRIAR TABELA DE DEMITIDOS
CREATE TABLE TAB_RH_DEMITIDOS (COD_FUNCIONARIO VARCHAR(5));

INSERT INTO TAB_RH_DEMITIDOS VALUES ('F0001');
INSERT INTO TAB_RH_DEMITIDOS VALUES ('F0005');
INSERT INTO TAB_RH_DEMITIDOS VALUES ('F0012');
INSERT INTO TAB_RH_DEMITIDOS VALUES ('F0022');
INSERT INTO TAB_RH_DEMITIDOS VALUES ('F0033');

SELECT * FROM TAB_RH_DEMITIDOS


--commando de commit mantém as alterações armazenadas no banco, sem precisar encerrar a sessão

update <tabela>
set <campo> = 'condição'
where <campo> = 'identificador'
COMMIT;--DEPOIS DE COMITAR A ALTERAÇÃO PASSARÁ A SER EFETIVADA NO BANCO 
