-- INDICA A ORDENAÇÃO DE ACORDO COM O CAMPO DEPOIS DO COMANDO
-- ASC PARA ASCENDENTE - DE FORMA CRESCENTE É DEFAULT
-- DESC PARA DECRESCENTE - FORMA DECRESCENTE

SELECT DISTINCT <LISTA DE CAMPOS OU *>
FROM <Nome da Tabela>
WHERE <Filtro>
AND ROWNUM <= <valor>
ORDER BY <campo> asc/desc

SELECT * FROM TINA_TB_PRODUTOS P
ORDER BY P.PRECO_DE_LISTA ASC -- DO MENOR PARA O MAIOR

SELECT * FROM TINA_TB_PRODUTOS P
WHERE P.NOME_DO_PRODUTO LIKE 'Linha%'
ORDER BY P.EMBALAGEM ASC, P.NOME_DO_PRODUTO DESC -- DO MAIOR PARA MENOR

--Utilizando duas queries SQL, qual foi a maior venda do produto Linha Refrescante - 1 Litro - Morango/Limao, em quantidade?

SELECT * FROM TINA_TB_ITENS_NOTAS_FISCAIS

SELECT P.CODIGO_DO_PRODUTO, P.NOME_DO_PRODUTO, INF.NUMERO, INF.QUANTIDADE, INF.PRECO
FROM TINA_TB_PRODUTOS P,TINA_TB_ITENS_NOTAS_FISCAIS INF
WHERE P.NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao'
AND P.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
ORDER BY INF.QUANTIDADE DESC

--Resolução
--Encontrar o código do produto e depois buscar ordenando pela quantidade na tabela de itens de nf
SELECT * FROM TABELA_DE_PRODUTOS 
WHERE nome_do_produto = 'Linha Refrescante - 1 Litro - Morango/Limao'

SELECT * FROM ITENS_NOTAS_FISCAIS
WHERE codigo_do_produto = '1101035'
ORDER BY QUANTIDADE DESC
