--HAVING ESTÁ ASSOCIADO A UMA CONSULTA QUE TENHA FILTRO SOBRE O RESULTADO DA AGREGAÇÃO 
--FILTRO DA SOMA QUE MOSTRA OS VALORES 
-- determina quais registros são exibidos:
SELECT <LISTA DE CAMPOS OU *>
FROM <Nome da Tabela>
WHERE SUM(CAMPO) >= x --FILTRO PARA MOSTRAR O RESULTADO
GROUP BY <CAMPO>
[HAVING critériosgrupo]

--HAVING, que vem como uma cláusula depois do GROUP BY, 
--Aplicando o filtro para limitar a saída do GROUP BY
SELECT ESTADO, 
SUM(NUM_FUNC) 
FROM CLIENTE 
GROUP BY ESTADO 
HAVING SUM(NUM_FUNC) >= 60 --filtro do resultado

SELECT * FROM TINA_TB_CLIENTES

SELECT ESTADO, 
SUM(LIMITE_DE_CREDITO) 
FROM TINA_TB_CLIENTES
GROUP BY ESTADO
HAVING SUM(LIMITE_DE_CREDITO) >= 60000

--NÃO VAI SER POSSÍVEL RODAR A CONSULTA POR QUE NÃO É POSSÍVEL FAZER O FILTRO DENTRO DO WHERE
SELECT ESTADO, 
SUM(LIMITE_DE_CREDITO) 
FROM TINA_TB_CLIENTES
WHERE SUM(LIMITE_DE_CREDITO) >= 90000 -- NÃO É POSSÍVEL FAZER O FILTRO DENTRO DO WHERE 
GROUP BY ESTADO

SELECT ESTADO, 
SUM(LIMITE_DE_CREDITO) 
FROM TINA_TB_CLIENTES
GROUP BY ESTADO
HAVING SUM(LIMITE_DE_CREDITO) >= 90000

SELECT Cidade, 
SUM(Quantidade) As TotalTeclados
FROM Vendas
WHERE Produto = 'Teclado'
GROUP BY Cidade
HAVING SUM(Quantidade) < 1500;

SELECT * FROM TINA_TB_PRODUTOS

SELECT * FROM TINA_TB_ITENS_NOTAS_FISCAIS
WHERE 


-- SELECIONA A EMBALAGEM DO PRODUTO QUE TEM O MAIOR E O MENOR PRECO_LISTA
SELECT EMBALAGEM, 
MAX(PRECO_DE_LISTA) AS MAIOR_PRECO, 
MIN(PRECO_DE_LISTA) AS MENOR_PRECO
FROM TINA_TB_PRODUTOS
WHERE PRECO_DE_LISTA >= 10 --FILTRA OD PRODUTOS COM O PREÇO MAIOR QUE 10
GROUP BY EMBALAGEM
HAVING MAX(PRECO_DE_LISTA) >=20 --AO EXECUTAR COM ESSE HAVING SERÃO MOSTRADOS OS PRODUTOS COM PRECO_LISTA MAIOR QUE 20


--Verifique as quantidades totais de vendas de cada produto e ordene da maior para a menor.

SELECT INF.CODIGO_DO_PRODUTO, P.NOME_DO_PRODUTO, INF.PRECO,
--SUM(INF.QUANTIDADE) AS QTDE_VENDA
FROM TINA_TB_PRODUTOS P, TINA_TB_ITENS_NOTAS_FISCAIS INF
WHERE P.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO
HAVING (INF.QUANTIDADE) > 20

--RESOLUCAO
SELECT CODIGO_DO_PRODUTO, 
SUM(QUANTIDADE) 
FROM TINA_TB_ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO 
ORDER BY SUM(QUANTIDADE) DESC;

--OUTRAS RESOLUÇÕES COM JOIN PARA MOSTRAR O NOME DO PRODUTO
select a.codigo_do_produto,b.nome_do_produto,a.quantidades from
(select codigo_do_produto ,sum(quantidade) as quantidades from tina_tb_itens_notas_fiscais --
group by codigo_do_produto
order by sum(quantidade) desc)a 
full join tina_tb_produtos b --
on a.codigo_do_produto = b.codigo_do_produto;--

SELECT B.CODIGO_DO_PRODUTO, a.nome_do_produto, 
SUM(B.QUANTIDADE) 
FROM TINA_TB_ITENS_NOTAS_FISCAIS B 
INNER JOIN TINA_TB_PRODUTOS A --
ON A.CODIGO_DO_PRODUTO = B.CODIGO_DO_PRODUTO --
GROUP BY B.CODIGO_DO_PRODUTO, a.nome_do_produto 
ORDER BY SUM(B.QUANTIDADE) DESC;

SELECT 
    tp.nome_do_produto,
    nf.codigo_do_produto,
    sum(nf.quantidade)

from tina_tb_itens_notas_fiscais nf
inner join tina_tb_produtos tp --
on tp.codigo_do_produto = nf.codigo_do_produto --
group by 
    nf.codigo_do_produto,
    tp.nome_do_produto
order by
    tp.nome_do_produto,
    sum(nf.quantidade)
    desc

-- 2) Vimos os produtos mais vendidos na atividade anterior. Agora, liste somente os produtos que venderam mais que 394000 litros.

SELECT * FROM TINA_TB_PRODUTOS -- TAMANHO: 350 ml, 470 ml, 700 ml, 1 Litro, 1,5 Litros, 2 Litros

SELECT CODIGO_DO_PRODUTO, 
SUM(QUANTIDADE) 
FROM TINA_TB_ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO 
ORDER BY SUM(QUANTIDADE) DESC
HAVING (QUANTIDADE) >= 20

SELECT B.CODIGO_DO_PRODUTO, a.nome_do_produto, 
SUM(B.QUANTIDADE) 
FROM TINA_TB_ITENS_NOTAS_FISCAIS B 
INNER JOIN TINA_TB_PRODUTOS A --
ON A.CODIGO_DO_PRODUTO = B.CODIGO_DO_PRODUTO --
GROUP BY B.CODIGO_DO_PRODUTO, a.nome_do_produto 
ORDER BY SUM(B.QUANTIDADE) DESC;
