--ROWNUM MOSTRA A QUANTIDADE DE REGISTROS DE ACORDO COM O ESTIPULADO SEM ALTERNAR REGISTROS 

SELECT ROWNUM, NOME_DO_PRODUTO FROM TINA_TB_PRODUTOS
WHERE SABOR = 'Maca'
and ROWNUM <= 5; --limitou a mostrar apenas os 5 primeiros registros


-- QUANDO INERIDO A ALIAS 
SELECT ROWNUM, TP.* FROM TINA_TB_PRODUTOS TP WHERE ROWNUM <= 5;

-- NÃO É NECESSÁRIO EXPLICITAR O ROWNUM NO FILTRO
SELECT TP.* FROM TINA_TB_PRODUTOS TP 
WHERE ROWNUM < 20 
ORDER BY tp.codigo_do_produto desc.


--Qual é o comando SQL para listar as 10 primeiras vendas do dia 01/10/2017?
--SELECIONA TODOS OS CAMPO DA TABELA DE NOTA FISCAL MOSTRANDO REGISTROS QUANDO A DATA DE VENDA 
SELECT * 
FROM TINA_TB_NOTAS_FISCAIS 
WHERE DATA_VENDA = TO_DATE('2017-01-01','YYYY-MM-DD') 
AND ROWNUM <= 10;

