--campos numericos para serem agrupados
SELECT DISTINCT <LISTA DE CAMPOS OU *>
FROM <Nome da Tabela>
where <Filtro>
and Rownum <= <valor>
GROUP BY <campos> --ANTES DO FILTRO e depois do order by
order by <campo> asc/desc

SELECT * FROM TINA_TB_NOTAS_FISCAIS

SELECT Matricula,
SUM(IMPOSTO)--SOMA A QUANTIDADE DE CAMPOS COM O VALOR
FROM TINA_TB_NOTAS_FISCAIS
GROUP BY Matricula

SELECT CIDADE, 
MIN(IDADE)--Menor valor do campo idade de acordo com as cidades dos clientes
FROM TINA_TB_CLIENTES
GROUP BY CIDADE 

SELECT CIDADE, 
MAX(IDADE)--Maior valor do campo idade de acordo com as cidades dos clientes
FROM TINA_TB_CLIENTES
GROUP BY CIDADE 

SELECT CIDADE,
AVG(IDADE) --media dos calores d
FROM TINA_TB_CLIENTES
GROUP BY CIDADE 

SELECT EMBALAGEM, 
MAX(PRECO_DE_LISTA) 
FROM TINA_TB_PRODUTOS 
GROUP BY EMBALAGEM

SELECT EMBALAGEM, 
MIN(PRECO_DE_LISTA) 
FROM TINA_TB_PRODUTOS 
GROUP BY EMBALAGEM


-- SELECIONA AS EMBALAGEM DOS PRODUTOS e CONTA A QTDE DE PRODUTOS
SELECT EMBALAGEM, COUNT(*) 
FROM TINA_TB_PRODUTOS 
GROUP BY EMBALAGEM 
ORDER BY EMBALAGEM;

-- SELECIONA A QUANTIDADE DOS PRODUTOS DE ACORDO COM A EMBALAGEM
SELECT EMBALAGEM, COUNT(*) AS QTDE_PRODUTO 
FROM TINA_TB_PRODUTOS 
GROUP BY EMBALAGEM 
ORDER BY EMBALAGEM;

--SELECIONA OS PRODUTOS COM UM TIPO DE EMBALAGEM E SABOR LARANJA 
SELECT EMBALAGEM, COUNT(*) AS NUMERO_DE_PRODUTOS 
FROM TINA_TB_PRODUTOS 
WHERE SABOR = 'Laranja'
GROUP BY EMBALAGEM 
ORDER BY EMBALAGEM;

SELECT P.CODIGO_DO_PRODUTO, P.NOME_DO_PRODUTO, INF.NUMERO, INF.QUANTIDADE, INF.PRECO
FROM TINA_TB_PRODUTOS P,TINA_TB_ITENS_NOTAS_FISCAIS INF
WHERE P.NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao'
AND P.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
ORDER BY INF.QUANTIDADE DESC

SELECT T.CODIGO_DO_PRODUTO, COUNT(*) 
FROM TINA_TB_ITENS_NOTAS_FISCAIS t
WHERE CODIGO_DO_PRODUTO = 1101035
AND QUANTIDADE = 99
GROUP BY CODIGO_DO_PRODUTO

--Quantas vendas foram feitas com quantidade igual a 99 litros para o produto 1101035?

SELECT CODIGO_DO_PRODUTO, COUNT(*) AS QTDE_VENDAS
FROM TINA_TB_ITENS_NOTAS_FISCAIS
WHERE CODIGO_DO_PRODUTO = 1101035
AND QUANTIDADE = 99
GROUP BY CODIGO_DO_PRODUTO

SELECT quantidade,
COUNT(*)
FROM TINA_TB_ITENS_NOTAS_FISCAIS
WHERE codigo_do_produto = '1101035'
AND quantidade = 99
GROUP BY quantidade;


--Resolução
SELECT COUNT(*) FROM TINA_TB_ITENS_NOTAS_FISCAIS WHERE codigo_do_produto = '1101035' AND quantidade = 99;

