SELECT * FROM TINA_TB_PRODUTOS P
WHERE P.Sabor IN ('Lima/Limao', 'Morango/Limao');

SELECT * FROM TINA_TB_PRODUTOS P WHERE P.Sabor like '%Limao'
SELECT * FROM TINA_TB_PRODUTOS P WHERE P.Sabor like 'Limao%'
SELECT * FROM TINA_TB_PRODUTOS P WHERE P.Sabor like '%_o'
SELECT * FROM TINA_TB_PRODUTOS P WHERE P.Sabor like '_a%'

SELECT * FROM TINA_TB_CLIENTES C WHERE C.NOME LIKE '%Silva'
