CREATE OR REPLACE PROCEDURE TINA_PRC_INCLUINDO_PRODUTO 
(p_COD TINA_TB_PRODUTOS.CODIGO_DO_PRODUTO%type
, p_NOME TINA_TB_PRODUTO.NOME_DO_PRODUTO%type
, p_EMBALAGEM TINA_TB_PRODUTO.EMBALAGEM%type
, p_TAMANHO TINA_TB_PRODUTO.TAMANHO%type
, p_SABOR TINA_TB_PRODUTO.SABOR%type
, p_PRECO TINA_TB_PRODUTO.PRECO_DE_LISTA%type)
IS
BEGIN
   INSERT INTO TINA_TB_PRODUTOS 
   (CODIGO_DO_PRODUTO, NOME_DO_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA) 
   VALUES 
   (p_COD,p_NOME, p_EMBALAGEM, p_TAMANHO, p_SABOR, p_PRECO);
   COMMIT;
END;

SELECT * FROM TINA_TB_PRODUTOS
