CREATE OR REPLACE PROCEDURE TINA_PRC_ALTERA_PRODUTO
(p_COD TINA_TB_PRODUTOS.CODIGO_DO_PRODUTO%type
, p_NOME TINA_TB_PRODUTO.NOME_DO_PRODUTO%type)
IS
BEGIN
   UPDATE TINA_TB_PRODUTOS SET NOME_DO_PRODUTO = p_NOME WHERE CODIGO_DO_PRODUTO = P_COD;
   COMMIT;
END;
