SELECT * FROM TINA_PRODUTOS 
--INSERE OS PRODUTOS DA TINA_TB_PRODUTOS PARA A TINA_PRODUTOS
INSERT INTO TINA_PRODUTOS
SELECT CODIGO_DO_PRODUTO AS CODIGO,
NOME_DO_PRODUTO AS DESCRICAO,
SABOR,
TAMANHO,
EMBALAGEM,
PRECO_DE_LISTA AS PRECO_LISTA
FROM TINA_TB_PRODUTOS --INSERINDO CONDIÇÃO PARA NEGAR "WHERE NOT"
WHERE NOT (CODIGO_DO_PRODUTO IN (
--VERIFICA A CONSULTA DAS DUAS TABELAS SE TRAZEM O CÓDIGO DO PRODUTO IGUAL
SELECT 
P.CODIGO
FROM 
TINA_PRODUTOS P
INNER JOIN TINA_TB_PRODUTOS TP
ON P.CODIGO = TP.CODIGO_DO_PRODUTO));

