--IDENTITY - NUMERO INTEIRO CRESCENTE
-- Se o campo não estiver no comando INSERT, 
--o valor que será incluído será o padrão definido na criação da tabela.
--O campo estará preenchido com o seu padrão, caso ele não seja declarado no INSERT.
--Um campo de Identity por tabela
--forçar o valor do autoincremento no Insert

CREATE TABLE TINA_TB_IDENTITY
(
ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
DESCRICAO VARCHAR(20),
PRIMARY KEY(ID));


-- GENERATED BY DEFAULT ON NULL AS IDENTITY - gerar o campo Identity como padrão
SELECT * FROM TINA_TB_IDENTITY

INSERT INTO TINA_TB_IDENTITY (DESCRICAO) VALUES ('CLIENTE 1') --Qndo inserir o cliente será atribuído o numero 1

INSERT INTO TINA_TB_IDENTITY (DESCRICAO) VALUES ('CLIENTE 2')

INSERT INTO TINA_TB_IDENTITY (DESCRICAO) VALUES ('CLIENTE 3')

DELETE FROM TINA_TB_IDENTITY WHERE ID = 2

INSERT INTO TINA_TB_IDENTITY (DESCRICAO) VALUES ('CLIENTE 4')

DELETE FROM TINA_TB_IDENTITY WHERE ID = 4

INSERT INTO TINA_TB_IDENTITY (DESCRICAO) VALUES ('CLIENTE 5')

SELECT * FROM TINA_TB_IDENTITY
--ao incluir o registro forçando o ID 7, a sequencia é quebrada
INSERT INTO TINA_TB_IDENTITY (ID,DESCRICAO) VALUES (7,'CLIENTE 7')

SELECT * FROM TINA_TB_IDENTITY

--Ao incluir um novo registro, ocorrerá erro de restrição, por que o id 7 foi inserido manualmente.
--se fazer a inserção novamente pula o id para o próximo da última inclusão.
INSERT INTO TINA_TB_IDENTITY (DESCRICAO) VALUES ('CLIENTE 6')
