--A trigger traduzindo do inglês para o português seria “gatilho”, é um tipo especial 
--de procedimento que está armazenado dentro do banco e que esse procedimento vai ser executado 
--automaticamente quando um evento ocorrer lá no servidor do banco de dados. 
--EVENTO DE INCLUSÃO, ALTERAÇÃO OU EXCLUSÃO
--TRIGGER ANTES DO INSERT OU DEPOIS DO INSERT

SELECT * FROM TINA_TB_CLIENTES --1471156710

SELECT * FROM TINA_TB_VENDEDORES --00235

SELECT * FROM TINA_TB_PRODUTOS --1000889

SELECT * FROM TINA_TB_NOTAS_FISCAIS
WHERE DATA_VENDA >= to_date('2023-01-01', 'yyyy-mm-dd')

SELECT * FROM TINA_TB_ITENS_NOTAS_FISCAIS
WHERE NUMERO = 2

--INSERINDO NOTA 1
INSERT INTO TINA_TB_NOTAS_FISCAIS
(NUMERO, DATA_VENDA,CPF,MATRICULA,IMPOSTO)
VALUES('001', to_date('2023-01-01', 'yyyy-mm-dd'), '1471156710', '00235', 0.1);

INSERT INTO TINA_TB_ITENS_NOTAS_FISCAIS 
(NUMERO, CODIGO_DO_PRODUTO, QUANTIDADE, PRECO) 
VALUES ('001','1000889',15,10); 

--INSERINDO NOTA 2
INSERT INTO TINA_TB_NOTAS_FISCAIS
(NUMERO, DATA_VENDA,CPF,MATRICULA,IMPOSTO)
VALUES('002', to_date('2023-01-01', 'yyyy-mm-dd'), '1471156710', '00235', 0.1);

INSERT INTO TINA_TB_ITENS_NOTAS_FISCAIS 
(NUMERO, CODIGO_DO_PRODUTO, QUANTIDADE, PRECO) 
VALUES ('002','1000889',15,10);

--INSERE A NOTA3
INSERT INTO TINA_TB_NOTAS_FISCAIS
(NUMERO, DATA_VENDA,CPF,MATRICULA,IMPOSTO)
VALUES('003', to_date('2023-01-02', 'yyyy-mm-dd'), '1471156710', '00235', 0.1);

INSERT INTO TINA_TB_ITENS_NOTAS_FISCAIS 
(NUMERO, CODIGO_DO_PRODUTO, QUANTIDADE, PRECO) 
VALUES ('003','1000889',18,10.5);

SELECT * FROM TINA_TB_NOTAS_FISCAIS
WHERE NUMERO = 003

SELECT * FROM TINA_TB_ITENS_NOTAS_FISCAIS
WHERE NUMERO = 003

--CONSULTA A NOTA COM O ITEM INSERIDO
SELECT 
NF.NUMERO, NF.DATA_VENDA, NF.CPF, NF.MATRICULA, NF.IMPOSTO,
ITNF.CODIGO_DO_PRODUTO, ITNF.QUANTIDADE, ITNF.PRECO
FROM TINA_TB_NOTAS_FISCAIS NF
INNER JOIN TINA_TB_ITENS_NOTAS_FISCAIS ITNF
ON NF.NUMERO = ITNF.NUMERO
INNER JOIN TINA_TB_PRODUTOS TP
ON TP.CODIGO_DO_PRODUTO = ITNF.CODIGO_DO_PRODUTO
WHERE NF.DATA_VENDA >= TO_DATE('2022-01-01', 'yyyy-mm-dd')

---Consultar o faturamento por data_VENDA
SELECT n.data_venda, 
sum(itn.quantidade * itn.preco) as faturamento --QTDE_VEND * PREÇO
from TINA_TB_NOTAS_FISCAIS N 
inner join TINA_TB_ITENS_NOTAS_FISCAIS ITN 
on n.numero = itn.numero 
WHERE N.DATA_VENDA >= TO_DATE('2022-01-01', 'yyyy-mm-dd')
group by n.data_venda;


--guardar o faturamento
CREATE TABLE TINA_TB_FATURAMENTO (DATA_VENDA DATE NULL, FATURAMENTO FLOAT);

SELECT * FROM TINA_TB_FATURAMENTO
WHERE DATA_VENDA >= TO_DATE('2022-01-01', 'yyyy-mm-dd')

--RESULTADO DO SELECT VAI SER INCLUIDO NA TABELA DE FATURAMENTO
INSERT INTO TINA_TB_FATURAMENTO
(SELECT nf.data_venda, 
  SUM(itn.quantidade * itn.preco) AS faturamento 
  FROM TINA_TB_NOTAS_FISCAIS nf 
  INNER JOIN TINA_TB_ITENS_NOTAS_FISCAIS itn 
  ON nf.numero = itn.numero 
  GROUP BY nf.data_venda);
  
  
SELECT * FROM TINA_TB_FATURAMENTO
WHERE DATA_VENDA >= TO_DATE('2023-01-01', 'yyyy-mm-dd')

--INSERE A NOTA 4
INSERT INTO TINA_TB_NOTAS_FISCAIS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES('004', to_date('2023-01-02', 'yyyy-mm-dd'), '1471156710', '00235', 0.10);

INSERT INTO TINA_TB_ITENS_NOTAS_FISCAIS (NUMERO, CODIGO_DO_PRODUTO, QUANTIDADE, PRECO) 
VALUES ('004','1000889',18,21.10);

--DEPOIS DE INCLUIR O ITEM 004 DEVERÁ DELETAR 
DELETE FROM TINA_TB_FATURAMENTO;
INSERT INTO TINA_TB_FATURAMENTO
(SELECT nf.data_venda, 
  SUM(itn.quantidade * itn.preco) AS faturamento 
  FROM TINA_TB_NOTAS_FISCAIS nf 
  INNER JOIN TINA_TB_ITENS_NOTAS_FISCAIS itn 
  ON nf.numero = itn.numero 
  GROUP BY nf.data_venda);
  
SELECT * FROM TINA_TB_FATURAMENTO
WHERE DATA_VENDA >= TO_DATE('2022-01-01', 'yyyy-mm-dd')
