INSERT INTO TINA_TB_SELLER
(ID_SELLER, NM_SELLER, VL_COMISSION_PERC)
VALUES
('00237','José Geraldo da Fonseca', 0.10);

INSERT INTO TINA_TB_SELLER
(ID_SELLER, NM_SELLER, VL_COMISSION_PERC)
VALUES
('00235','Márcio Almeida Silva', 0.08);

INSERT INTO TINA_TB_SELLER
(ID_SELLER, NM_SELLER, VL_COMISSION_PERC)
VALUES
('00236','Cláudia Morais', 0.10);

SELECT * FROM TINA_TB_SELLER
