CREATE TABLE TB_SELLER
(ID_SELLER VARCHAR(5),
NM_SELLER VARCHAR(100),
VL_COMIS_PERC NUMBER(3,2))

ALTER TABLE TB_SELLER ADD CONSTRAINT PK_TB_SELLER PRIMARY KEY (ID_SELLER);

ALTER TABLE TB_SELLER
RENAME TO TINA_TB_SELLER

ALTER TABLE TINA_TB_SELLER
RENAME COLUMN NAME_SELLER TO NM_SELLER

ALTER TABLE TINA_TB_SELLER
RENAME COLUMN VL_COMIS_PERC TO VL_COMISSION_PERC

SELECT * FROM TINA_TB_SELLER



